### ISSUE TITLE
RequestManualMode example

### ISSUE THREAD

**Issue by TomW-Skyline** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#13]
Add a good example to the summary tag of the RequestManualMode method, using `<example>...</example>`.
See https://community.dataminer.services/question/requestmanualmode-action/

This example should automatically appear here:
https://docs.dataminer.services/develop/api/types/Skyline.DataMiner.Utils.InteractiveAutomationScript.InteractiveController.RequestManualMode.html

**Comment by ThomasRemmery** [comment]
Moved issues to IAS example package: [RequestManualMode example](https://github.com/SkylineCommunications/SLC-AS-Example_InteractiveAutomationScriptToolkit/issues/2).
