### ISSUE TITLE
Support for DebugTag (RN39365)

### ISSUE THREAD

**Issue by VanRobaysWouter** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#17]
In DataMiner 10.4.7, a DebugTag property is added on the UIBlockDefinition allowing to identify UI elements in automated tests. This has been added with RN39365

**Comment by ThomasRemmery** [comment]
Hi Wouter, support for the DebugTag is available from [9.0.1](https://github.com/SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit/releases/tag/9.0.1) onwards. Thanks for keeping us aware of new updates.
