### ISSUE TITLE
Add support for SkipAbortConfirmation (RN40683)

### ISSUE THREAD

**Issue by VanRobaysWouter** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#18]
Upcoming feature for IAS in RN40683: the SkipAbortConfirmation on the UIBuilder will allow you to skip the confirmation popup when aborting the script if set to true.

Will post update here when this feature is merged and the release version is known.

**Comment by VanRobaysWouter** [comment]
Property will be available in DM 10.4.12

**Comment by ThomasRemmery** [comment]
Available as prerelease from [10.0.1-prerelease.1](https://github.com/SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit/releases/tag/10.0.1-prerelease.1) onwards.

**Comment by ThomasRemmery** [comment]
Officially released in [10.0.1](https://github.com/SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit/releases/tag/10.0.1).
