### ISSUE TITLE
Hyperlink component

### ISSUE THREAD

**Issue by TomW-Skyline** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#19]
A hyperlink component would be very useful:
https://community.dataminer.services/question/interactive-automation-script-how-to-display-a-clickable-hyperlink/answer/133733/

**Comment by ThomasRemmery** [comment]
Available from [9.0.4](https://github.com/SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit/releases/tag/9.0.4) onwards.
