### ISSUE TITLE
DownloadButton missing

### ISSUE THREAD

**Issue by Niwreg** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#3]
Hi,

With the release of 10.3.7 there is an UIBlocktype of DownloadButton availble. However that is not (yet) included in the NuGet package for IAS. Is it possible to add this as well?

**Comment by ThomasRemmery** [comment]
Hi,

The DownloadButton feature was made available in 7.0.1.

**Comment by ThomasRemmery** [comment]
Hi,

The DownloadButton feature was made available in 7.0.1.
