### ISSUE TITLE
Section.AddWidget does not indicate what the position of the already added widget is in the exception

### ISSUE THREAD

**Issue by VictorScherpereell** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#4]
When getting the exception 
System.ArgumentException: Widget is already added to the section
at Skyline.DataMiner.Utils.InteractiveAutomationScript.Section.AddWidget(Widget widget, IWidgetLayout widgetLayout)

It would be useful to have some kind of indication for which widget this exception is thrown by mentioning the position of the already added widget in the exception message.

**Comment by ThomasRemmery** [comment]
The OverlappingWidgetsException contains the position of the overlapping widgets. This feature was implemented in all versions of the toolkit.
