### ISSUE TITLE
Add support for IsReadOnly property (RN 37659)

### ISSUE THREAD

**Issue by slc-peter-vanpoucke** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#5]
Added this issue to inform you about this upcoming change: RN37659 will add support to render some components read-only in web.

**Comment by slc-peter-vanpoucke** [comment]
Merged, will be released in 10.4.1.

**Comment by ThomasRemmery** [comment]
IsReadOnly will be included in 8.0.1 release.

**Comment by ThomasRemmery** [comment]
8.0.1 has been released.
