### ISSUE TITLE
Add Controller.Stop() method

### ISSUE THREAD

**Issue by Ivehe** [SkylineCommunications/Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit#8]
Currently, when the Controller.Start() method is called, the script remains in a while loop, that can never be left.
Add a method Controller.Stop() which would allow to leave the while loop.

**Comment by ThomasRemmery** [comment]
You can leave the loop by throwing an exception from any of the shown dialogs or events triggered by interactive widgets. For the sake of completeness a stop method has been added to the InteractiveController class. This will be included in 8.0.1 once released and backported to previous versions.

**Comment by ThomasRemmery** [comment]
A stop method has been added to the InteractiveController. This feature has been included in all ranges and released.
